# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'dirs/**.gml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
          architecture: 'x64'
      - name: Install dependencies
      - run: python -m pip install --upgrade pip setuptools wheel
      - name: Run Script
      - run: python numetric_char_str.py
      - name: Run a multi-line script
      - run: |
          git config user.name ${NAME}
          git config user.email ${EMAIL}
          git remote set-url origin https://${NAME}:${{ secrets.USER_GITHUB }}@github.com/${NAME}/${REPO}
          git add .
          git commit -m "create escape gml file"
          git pull
          git push origin master
      - env:
          NAME: Villager-B
          EMAIL: kkss07020@gmail.com
          REPO: github-action-training
